import { z } from "zod";

const envSchema = z.object({
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  NEXT_PUBLIC_SUPABASE_URL: z.string().url().optional(),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
  DATABASE_URL: z.string().optional(),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_MODEL: z.string().default("gpt-4.1-mini"),
  ANTHROPIC_KEY: z.string().optional(),
  ANTHROPIC_MODEL: z.string().default("claude-opus-4-8"),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  GOOGLE_REDIRECT_URI: z.string().optional(),
  SLACK_WEBHOOK_URL: z.string().optional(),
  CRON_SECRET: z.string().optional(),
  ZENROWS_API_KEY: z.string().optional(),
  BRIGHTDATA_API_TOKEN: z.string().optional(),
  BRIGHTDATA_ZONE: z.string().optional(),
  LEAD_ENRICHMENT_ENABLED: z.string().optional(),
  DEFAULT_FORWARDING_INBOX: z.string().email().default("humayun.jawad@datumlabs.io"),
  DEFAULT_NOTIFICATION_EMAIL: z.string().email().default("humayun.jawad@datumlabs.io"),
});

export const env = envSchema.parse({
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  DATABASE_URL: process.env.DATABASE_URL,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_MODEL: process.env.OPENAI_MODEL,
  ANTHROPIC_KEY: process.env.ANTHROPIC_KEY,
  ANTHROPIC_MODEL: process.env.ANTHROPIC_MODEL,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
  SLACK_WEBHOOK_URL: process.env.SLACK_WEBHOOK_URL,
  CRON_SECRET: process.env.CRON_SECRET,
  ZENROWS_API_KEY: process.env.ZENROWS_API_KEY,
  BRIGHTDATA_API_TOKEN: process.env.BRIGHTDATA_API_TOKEN,
  BRIGHTDATA_ZONE: process.env.BRIGHTDATA_ZONE,
  LEAD_ENRICHMENT_ENABLED: process.env.LEAD_ENRICHMENT_ENABLED,
  DEFAULT_FORWARDING_INBOX: process.env.DEFAULT_FORWARDING_INBOX,
  DEFAULT_NOTIFICATION_EMAIL: process.env.DEFAULT_NOTIFICATION_EMAIL,
});
